### PR TITLE
Remove S-awaiting-merge label once issues are merged. Issue #77

### PR DESCRIPTION
**Pull request by Mylainos**
Fixes for this issue https://github.com/servo/highfive/issues/77

### CODE REVIEW

**Comment by jdm** [comment]
Nice! Please squash the commits and I'll merge them :)

**Comment by Mylainos** [comment]
Don't we need a new test ?

**Comment by jdm** [comment]
Oh yeah, that would be useful :)

**Comment by jdm** [comment]
Here's JSON payload from a PR that was just merged.
```
{
  "action": "closed",
  "number": 10315,
  "pull_request": {
    "url": "https://api.github.com/repos/servo/servo/pulls/10315",
    "id": 64823910,
    "html_url": "https://github.com/servo/servo/pull/10315",
    "diff_url": "https://github.com/servo/servo/pull/10315.diff",
    "patch_url": "https://github.com/servo/servo/pull/10315.patch",
    "issue_url": "https://api.github.com/repos/servo/servo/issues/10315",
    "number": 10315,
    "state": "closed",
    "locked": false,
    "title": "Update web-platform-tests to 5582e4d2bfcfd1fa9f105406b143170ee2af7db1",
    "user": {
      "login": "jgraham",
      "id": 294864,
      "avatar_url": "https://avatars.githubusercontent.com/u/294864?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jgraham",
      "html_url": "https://github.com/jgraham",
      "followers_url": "https://api.github.com/users/jgraham/followers",
      "following_url": "https://api.github.com/users/jgraham/following{/other_user}",
      "gists_url": "https://api.github.com/users/jgraham/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jgraham/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jgraham/subscriptions",
      "organizations_url": "https://api.github.com/users/jgraham/orgs",
      "repos_url": "https://api.github.com/users/jgraham/repos",
      "events_url": "https://api.github.com/users/jgraham/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jgraham/received_events",
      "type": "User",
      "site_admin": false
    },
    "body": "\n\n<!-- Reviewable:start -->\nThis change is [<img src=\"https://reviewable.io/review_button.svg\" height=\"35\" align=\"absmiddle\" alt=\"Reviewable\"/>](https://reviewable.io/reviews/servo/servo/10315)\n<!-- Reviewable:end -->\n",
    "created_at": "2016-03-31T17:00:00Z",
    "updated_at": "2016-04-01T13:44:52Z",
    "closed_at": "2016-04-01T13:44:52Z",
    "merged_at": "2016-04-01T13:44:52Z",
    "merge_commit_sha": "78369e95cf7ed0813cb9342747caa4984ae7c527",
    "assignee": {
      "login": "pcwalton",
      "id": 157897,
      "avatar_url": "https://avatars.githubusercontent.com/u/157897?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/pcwalton",
      "html_url": "https://github.com/pcwalton",
      "followers_url": "https://api.github.com/users/pcwalton/followers",
      "following_url": "https://api.github.com/users/pcwalton/following{/other_user}",
      "gists_url": "https://api.github.com/users/pcwalton/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/pcwalton/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/pcwalton/subscriptions",
      "organizations_url": "https://api.github.com/users/pcwalton/orgs",
      "repos_url": "https://api.github.com/users/pcwalton/repos",
      "events_url": "https://api.github.com/users/pcwalton/events{/privacy}",
      "received_events_url": "https://api.github.com/users/pcwalton/received_events",
      "type": "User",
      "site_admin": false
    },
    "milestone": null,
    "commits_url": "https://api.github.com/repos/servo/servo/pulls/10315/commits",
    "review_comments_url": "https://api.github.com/repos/servo/servo/pulls/10315/comments",
    "review_comment_url": "https://api.github.com/repos/servo/servo/pulls/comments{/number}",
    "comments_url": "https://api.github.com/repos/servo/servo/issues/10315/comments",
    "statuses_url": "https://api.github.com/repos/servo/servo/statuses/78369e95cf7ed0813cb9342747caa4984ae7c527",
    "head": {
      "label": "jgraham:update-wpt",
      "ref": "update-wpt",
      "sha": "78369e95cf7ed0813cb9342747caa4984ae7c527",
      "user": {
        "login": "jgraham",
        "id": 294864,
        "avatar_url": "https://avatars.githubusercontent.com/u/294864?v=3",
        "gravatar_id": "",
        "url": "https://api.github.com/users/jgraham",
        "html_url": "https://github.com/jgraham",
        "followers_url": "https://api.github.com/users/jgraham/followers",
        "following_url": "https://api.github.com/users/jgraham/following{/other_user}",
        "gists_url": "https://api.github.com/users/jgraham/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/jgraham/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/jgraham/subscriptions",
        "organizations_url": "https://api.github.com/users/jgraham/orgs",
        "repos_url": "https://api.github.com/users/jgraham/repos",
        "events_url": "https://api.github.com/users/jgraham/events{/privacy}",
        "received_events_url": "https://api.github.com/users/jgraham/received_events",
        "type": "User",
        "site_admin": false
      },
      "repo": {
        "id": 12646114,
        "name": "servo",
        "full_name": "jgraham/servo",
        "owner": {
          "login": "jgraham",
          "id": 294864,
          "avatar_url": "https://avatars.githubusercontent.com/u/294864?v=3",
          "gravatar_id": "",
          "url": "https://api.github.com/users/jgraham",
          "html_url": "https://github.com/jgraham",
          "followers_url": "https://api.github.com/users/jgraham/followers",
          "following_url": "https://api.github.com/users/jgraham/following{/other_user}",
          "gists_url": "https://api.github.com/users/jgraham/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/jgraham/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/jgraham/subscriptions",
          "organizations_url": "https://api.github.com/users/jgraham/orgs",
          "repos_url": "https://api.github.com/users/jgraham/repos",
          "events_url": "https://api.github.com/users/jgraham/events{/privacy}",
          "received_events_url": "https://api.github.com/users/jgraham/received_events",
          "type": "User",
          "site_admin": false
        },
        "private": false,
        "html_url": "https://github.com/jgraham/servo",
        "description": "The Servo Browser Engine",
        "fork": true,
        "url": "https://api.github.com/repos/jgraham/servo",
        "forks_url": "https://api.github.com/repos/jgraham/servo/forks",
        "keys_url": "https://api.github.com/repos/jgraham/servo/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/jgraham/servo/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/jgraham/servo/teams",
        "hooks_url": "https://api.github.com/repos/jgraham/servo/hooks",
        "issue_events_url": "https://api.github.com/repos/jgraham/servo/issues/events{/number}",
        "events_url": "https://api.github.com/repos/jgraham/servo/events",
        "assignees_url": "https://api.github.com/repos/jgraham/servo/assignees{/user}",
        "branches_url": "https://api.github.com/repos/jgraham/servo/branches{/branch}",
        "tags_url": "https://api.github.com/repos/jgraham/servo/tags",
        "blobs_url": "https://api.github.com/repos/jgraham/servo/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/jgraham/servo/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/jgraham/servo/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/jgraham/servo/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/jgraham/servo/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/jgraham/servo/languages",
        "stargazers_url": "https://api.github.com/repos/jgraham/servo/stargazers",
        "contributors_url": "https://api.github.com/repos/jgraham/servo/contributors",
        "subscribers_url": "https://api.github.com/repos/jgraham/servo/subscribers",
        "subscription_url": "https://api.github.com/repos/jgraham/servo/subscription",
        "commits_url": "https://api.github.com/repos/jgraham/servo/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/jgraham/servo/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/jgraham/servo/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/jgraham/servo/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/jgraham/servo/contents/{+path}",
        "compare_url": "https://api.github.com/repos/jgraham/servo/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/jgraham/servo/merges",
        "archive_url": "https://api.github.com/repos/jgraham/servo/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/jgraham/servo/downloads",
        "issues_url": "https://api.github.com/repos/jgraham/servo/issues{/number}",
        "pulls_url": "https://api.github.com/repos/jgraham/servo/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/jgraham/servo/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/jgraham/servo/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/jgraham/servo/labels{/name}",
        "releases_url": "https://api.github.com/repos/jgraham/servo/releases{/id}",
        "deployments_url": "https://api.github.com/repos/jgraham/servo/deployments",
        "created_at": "2013-09-06T14:28:47Z",
        "updated_at": "2015-06-18T13:12:48Z",
        "pushed_at": "2016-04-01T11:39:06Z",
        "git_url": "git://github.com/jgraham/servo.git",
        "ssh_url": "git@github.com:jgraham/servo.git",
        "clone_url": "https://github.com/jgraham/servo.git",
        "svn_url": "https://github.com/jgraham/servo",
        "homepage": "",
        "size": 181462,
        "stargazers_count": 0,
        "watchers_count": 0,
        "language": "Rust",
        "has_issues": false,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "forks_count": 0,
        "mirror_url": null,
        "open_issues_count": 0,
        "forks": 0,
        "open_issues": 0,
        "watchers": 0,
        "default_branch": "master"
      }
    },
    "base": {
      "label": "servo:master",
      "ref": "master",
      "sha": "9f892edd87441393e5de00790a5abb7fc93a09de",
      "user": {
        "login": "servo",
        "id": 2566135,
        "avatar_url": "https://avatars.githubusercontent.com/u/2566135?v=3",
        "gravatar_id": "",
        "url": "https://api.github.com/users/servo",
        "html_url": "https://github.com/servo",
        "followers_url": "https://api.github.com/users/servo/followers",
        "following_url": "https://api.github.com/users/servo/following{/other_user}",
        "gists_url": "https://api.github.com/users/servo/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/servo/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/servo/subscriptions",
        "organizations_url": "https://api.github.com/users/servo/orgs",
        "repos_url": "https://api.github.com/users/servo/repos",
        "events_url": "https://api.github.com/users/servo/events{/privacy}",
        "received_events_url": "https://api.github.com/users/servo/received_events",
        "type": "Organization",
        "site_admin": false
      },
      "repo": {
        "id": 3390243,
        "name": "servo",
        "full_name": "servo/servo",
        "owner": {
          "login": "servo",
          "id": 2566135,
          "avatar_url": "https://avatars.githubusercontent.com/u/2566135?v=3",
          "gravatar_id": "",
          "url": "https://api.github.com/users/servo",
          "html_url": "https://github.com/servo",
          "followers_url": "https://api.github.com/users/servo/followers",
          "following_url": "https://api.github.com/users/servo/following{/other_user}",
          "gists_url": "https://api.github.com/users/servo/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/servo/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/servo/subscriptions",
          "organizations_url": "https://api.github.com/users/servo/orgs",
          "repos_url": "https://api.github.com/users/servo/repos",
          "events_url": "https://api.github.com/users/servo/events{/privacy}",
          "received_events_url": "https://api.github.com/users/servo/received_events",
          "type": "Organization",
          "site_admin": false
        },
        "private": false,
        "html_url": "https://github.com/servo/servo",
        "description": "The Servo Browser Engine",
        "fork": false,
        "url": "https://api.github.com/repos/servo/servo",
        "forks_url": "https://api.github.com/repos/servo/servo/forks",
        "keys_url": "https://api.github.com/repos/servo/servo/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/servo/servo/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/servo/servo/teams",
        "hooks_url": "https://api.github.com/repos/servo/servo/hooks",
        "issue_events_url": "https://api.github.com/repos/servo/servo/issues/events{/number}",
        "events_url": "https://api.github.com/repos/servo/servo/events",
        "assignees_url": "https://api.github.com/repos/servo/servo/assignees{/user}",
        "branches_url": "https://api.github.com/repos/servo/servo/branches{/branch}",
        "tags_url": "https://api.github.com/repos/servo/servo/tags",
        "blobs_url": "https://api.github.com/repos/servo/servo/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/servo/servo/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/servo/servo/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/servo/servo/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/servo/servo/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/servo/servo/languages",
        "stargazers_url": "https://api.github.com/repos/servo/servo/stargazers",
        "contributors_url": "https://api.github.com/repos/servo/servo/contributors",
        "subscribers_url": "https://api.github.com/repos/servo/servo/subscribers",
        "subscription_url": "https://api.github.com/repos/servo/servo/subscription",
        "commits_url": "https://api.github.com/repos/servo/servo/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/servo/servo/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/servo/servo/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/servo/servo/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/servo/servo/contents/{+path}",
        "compare_url": "https://api.github.com/repos/servo/servo/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/servo/servo/merges",
        "archive_url": "https://api.github.com/repos/servo/servo/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/servo/servo/downloads",
        "issues_url": "https://api.github.com/repos/servo/servo/issues{/number}",
        "pulls_url": "https://api.github.com/repos/servo/servo/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/servo/servo/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/servo/servo/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/servo/servo/labels{/name}",
        "releases_url": "https://api.github.com/repos/servo/servo/releases{/id}",
        "deployments_url": "https://api.github.com/repos/servo/servo/deployments",
        "created_at": "2012-02-08T19:07:25Z",
        "updated_at": "2016-04-01T13:39:47Z",
        "pushed_at": "2016-04-01T13:44:49Z",
        "git_url": "git://github.com/servo/servo.git",
        "ssh_url": "git@github.com:servo/servo.git",
        "clone_url": "https://github.com/servo/servo.git",
        "svn_url": "https://github.com/servo/servo",
        "homepage": "https://servo.org/",
        "size": 213301,
        "stargazers_count": 6406,
        "watchers_count": 6406,
        "language": null,
        "has_issues": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "forks_count": 1054,
        "mirror_url": null,
        "open_issues_count": 1420,
        "forks": 1054,
        "open_issues": 1420,
        "watchers": 6406,
        "default_branch": "master"
      }
    },
    "_links": {
      "self": {
        "href": "https://api.github.com/repos/servo/servo/pulls/10315"
      },
      "html": {
        "href": "https://github.com/servo/servo/pull/10315"
      },
      "issue": {
        "href": "https://api.github.com/repos/servo/servo/issues/10315"
      },
      "comments": {
        "href": "https://api.github.com/repos/servo/servo/issues/10315/comments"
      },
      "review_comments": {
        "href": "https://api.github.com/repos/servo/servo/pulls/10315/comments"
      },
      "review_comment": {
        "href": "https://api.github.com/repos/servo/servo/pulls/comments{/number}"
      },
      "commits": {
        "href": "https://api.github.com/repos/servo/servo/pulls/10315/commits"
      },
      "statuses": {
        "href": "https://api.github.com/repos/servo/servo/statuses/78369e95cf7ed0813cb9342747caa4984ae7c527"
      }
    },
    "merged": true,
    "mergeable": null,
    "mergeable_state": "unknown",
    "merged_by": {
      "login": "bors-servo",
      "id": 4368172,
      "avatar_url": "https://avatars.githubusercontent.com/u/4368172?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/bors-servo",
      "html_url": "https://github.com/bors-servo",
      "followers_url": "https://api.github.com/users/bors-servo/followers",
      "following_url": "https://api.github.com/users/bors-servo/following{/other_user}",
      "gists_url": "https://api.github.com/users/bors-servo/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/bors-servo/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/bors-servo/subscriptions",
      "organizations_url": "https://api.github.com/users/bors-servo/orgs",
      "repos_url": "https://api.github.com/users/bors-servo/repos",
      "events_url": "https://api.github.com/users/bors-servo/events{/privacy}",
      "received_events_url": "https://api.github.com/users/bors-servo/received_events",
      "type": "User",
      "site_admin": false
    },
    "comments": 12,
    "review_comments": 0,
    "commits": 1,
    "additions": 1658,
    "deletions": 519,
    "changed_files": 895
  },
  "repository": {
    "id": 3390243,
    "name": "servo",
    "full_name": "servo/servo",
    "owner": {
      "login": "servo",
      "id": 2566135,
      "avatar_url": "https://avatars.githubusercontent.com/u/2566135?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/servo",
      "html_url": "https://github.com/servo",
      "followers_url": "https://api.github.com/users/servo/followers",
      "following_url": "https://api.github.com/users/servo/following{/other_user}",
      "gists_url": "https://api.github.com/users/servo/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/servo/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/servo/subscriptions",
      "organizations_url": "https://api.github.com/users/servo/orgs",
      "repos_url": "https://api.github.com/users/servo/repos",
      "events_url": "https://api.github.com/users/servo/events{/privacy}",
      "received_events_url": "https://api.github.com/users/servo/received_events",
      "type": "Organization",
      "site_admin": false
    },
    "private": false,
    "html_url": "https://github.com/servo/servo",
    "description": "The Servo Browser Engine",
    "fork": false,
    "url": "https://api.github.com/repos/servo/servo",
    "forks_url": "https://api.github.com/repos/servo/servo/forks",
    "keys_url": "https://api.github.com/repos/servo/servo/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/servo/servo/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/servo/servo/teams",
    "hooks_url": "https://api.github.com/repos/servo/servo/hooks",
    "issue_events_url": "https://api.github.com/repos/servo/servo/issues/events{/number}",
    "events_url": "https://api.github.com/repos/servo/servo/events",
    "assignees_url": "https://api.github.com/repos/servo/servo/assignees{/user}",
    "branches_url": "https://api.github.com/repos/servo/servo/branches{/branch}",
    "tags_url": "https://api.github.com/repos/servo/servo/tags",
    "blobs_url": "https://api.github.com/repos/servo/servo/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/servo/servo/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/servo/servo/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/servo/servo/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/servo/servo/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/servo/servo/languages",
    "stargazers_url": "https://api.github.com/repos/servo/servo/stargazers",
    "contributors_url": "https://api.github.com/repos/servo/servo/contributors",
    "subscribers_url": "https://api.github.com/repos/servo/servo/subscribers",
    "subscription_url": "https://api.github.com/repos/servo/servo/subscription",
    "commits_url": "https://api.github.com/repos/servo/servo/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/servo/servo/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/servo/servo/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/servo/servo/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/servo/servo/contents/{+path}",
    "compare_url": "https://api.github.com/repos/servo/servo/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/servo/servo/merges",
    "archive_url": "https://api.github.com/repos/servo/servo/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/servo/servo/downloads",
    "issues_url": "https://api.github.com/repos/servo/servo/issues{/number}",
    "pulls_url": "https://api.github.com/repos/servo/servo/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/servo/servo/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/servo/servo/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/servo/servo/labels{/name}",
    "releases_url": "https://api.github.com/repos/servo/servo/releases{/id}",
    "deployments_url": "https://api.github.com/repos/servo/servo/deployments",
    "created_at": "2012-02-08T19:07:25Z",
    "updated_at": "2016-04-01T13:39:47Z",
    "pushed_at": "2016-04-01T13:44:49Z",
    "git_url": "git://github.com/servo/servo.git",
    "ssh_url": "git@github.com:servo/servo.git",
    "clone_url": "https://github.com/servo/servo.git",
    "svn_url": "https://github.com/servo/servo",
    "homepage": "https://servo.org/",
    "size": 213301,
    "stargazers_count": 6406,
    "watchers_count": 6406,
    "language": null,
    "has_issues": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 1054,
    "mirror_url": null,
    "open_issues_count": 1420,
    "forks": 1054,
    "open_issues": 1420,
    "watchers": 6406,
    "default_branch": "master"
  },
  "organization": {
    "login": "servo",
    "id": 2566135,
    "url": "https://api.github.com/orgs/servo",
    "repos_url": "https://api.github.com/orgs/servo/repos",
    "events_url": "https://api.github.com/orgs/servo/events",
    "hooks_url": "https://api.github.com/orgs/servo/hooks",
    "issues_url": "https://api.github.com/orgs/servo/issues",
    "members_url": "https://api.github.com/orgs/servo/members{/member}",
    "public_members_url": "https://api.github.com/orgs/servo/public_members{/member}",
    "avatar_url": "https://avatars.githubusercontent.com/u/2566135?v=3",
    "description": null
  },
  "sender": {
    "login": "bors-servo",
    "id": 4368172,
    "avatar_url": "https://avatars.githubusercontent.com/u/4368172?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/bors-servo",
    "html_url": "https://github.com/bors-servo",
    "followers_url": "https://api.github.com/users/bors-servo/followers",
    "following_url": "https://api.github.com/users/bors-servo/following{/other_user}",
    "gists_url": "https://api.github.com/users/bors-servo/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/bors-servo/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/bors-servo/subscriptions",
    "organizations_url": "https://api.github.com/users/bors-servo/orgs",
    "repos_url": "https://api.github.com/users/bors-servo/repos",
    "events_url": "https://api.github.com/users/bors-servo/events{/privacy}",
    "received_events_url": "https://api.github.com/users/bors-servo/received_events",
    "type": "User",
    "site_admin": false
  }
}
```

**Comment by Mylainos** [comment]
Should I squash ?

**Comment by jdm** [comment]
No need!

**Pull request merged**
