### PR TITLE
Support file path exclusions in watcher handler. Issue #76

### PR DESCRIPTION
**Pull request by Mylainos**
I have used this https://docs.python.org/2/tutorial/controlflow.html#break-and-continue-statements-and-else-clauses-on-loops. I don't understand how the test work, how should I add one ?

### CODE REVIEW

**Comment by jdm** [comment]
Does https://github.com/servo/highfive#testing clear up the test format? The JSON files provide an initial state of the PR (such as the current assignee and labels), then process the given payload, and assert that the PR's final state matches the expected one (ie. number of comments added, assignee, labels, etc.).

**Comment by Mylainos** [comment]
I have seen this. The tests in `/handlers/watchers/tests/new_pr.json` are specifics, should I do something like that:
```
"diff": "diff --git a/watched/dir/file.rs /dev/null"
```
I don't understand what this mean and why he expect a number of comments.

**Comment by jdm** [comment]
Ah. That's a very simple mock of a PR diff that contains changes to a file that is watched (in this case, the `/dev/null` means that it's being deleted). The expected number of comments comes from the handler publishing a comment announcing that the PR changes a file that is being watched.

**Comment by Mylainos** [comment]
Should I squash ?

**Comment by jdm** [comment]
No need, github lets me do that. Thanks for the PR!

**Comment by jdm** [comment]
cc @jgraham

**Pull request merged**
